#! /bin/bash

# Creates a new python script template.

filename="${1}.py"

# Create script
echo "#! /soe/mollyzhang/anaconda/bin/python" >> $filename



day=$(date +%m/%d/%y)
time=$(date +%H:%M)
filenametrunc="${filename##*/}"
echo "\"\"\"$filenametrunc" >> $filename
echo "Created by Molly Zhang on $day at $time" >> $filename
echo "\"\"\"" >> $filename

echo "import sys" >> $filename
echo "import argparse" >> $filename

echo "" >> $filename
echo "def parse_args():" >> $filename
echo "    \"\"\"Set up and parse command-line arguments.\"\"\"" >> $filename
echo "    parser = argparse.ArgumentParser(\"description\")" >> $filename
echo "    parser.add_argument(\"argument1\", help = \"\")" >> $filename
echo "    return parser.parse_args()" >> $filename
echo "" >> $filename
echo "def main(args):" >> $filename
echo "    \"\"\"Main method\"\"\"" >> $filename
echo "    args = parse_args()" >> $filename

echo "" >> $filename
echo "if __name__ == \"__main__\" :" >> $filename
echo "    sys.exit(main(sys.argv))" >> $filename
echo "" >> $filename

# Make executable
chmod 775 $filename

